name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > /tmp/known_hosts
          chmod 600 /tmp/known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock

      - name: Start SSH agent
        run: |
          # Create a script to handle the passphrase
          echo '#!/bin/sh' > /tmp/ssh-askpass
          echo 'echo "${{ secrets.SSH_KEY_PASSPHRASE }}"' >> /tmp/ssh-askpass
          chmod +x /tmp/ssh-askpass
          
          # Set environment variables
          export SSH_ASKPASS=/tmp/ssh-askpass
          export DISPLAY=:0
          
          # Start SSH agent and add key
          eval "$(ssh-agent -s)"
          ssh-add /tmp/id_rsa
          ssh-add -l
        env:
          SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}

      - name: Deploy to server
        run: |
          scp -r . ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
